apiVersion: v1
kind: Service
metadata:
 name: contour
 namespace: heptio-contour
 annotations:
  # This annotation puts the AWS ELB into "TCP" mode so that it does not
  # to http negotiation at the ELB edge. This means the remote address of
  # all connectinos will appear to be the internal address of the ELB.
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  # To recover the remote ip 
  # 1. Add the --use-proxy-protocol flag to your deployment or daemonset's contour serve command.
  # 2. uncomment this line to enable PROXY protocol # on the ELB
  # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
 ports:
 - port: 80
   name: http
   protocol: TCP
   targetPort: 8080
 - port: 443
   name: https
   protocol: TCP
   targetPort: 8443
 selector:
   app: contour
 type: LoadBalancer
---
