[[constraint]]
  name = "github.com/gorilla/mux"
  version = "~1.5"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.2.1"

[[constraint]]
  name="k8s.io/client-go"
  version="~5.0"

[[constraint]]
  name="k8s.io/api"
  branch="release-1.8"

[[constraint]]
  name="google.golang.org/grpc"
  version="~1.8"

[[constraint]]
  name="k8s.io/apimachinery"
  branch="release-1.8"
